_target_: pangaea.datasets.faofra.FAOFRACd
dataset_name: FAOFRACd
root_path: ./data/faofracd
download_url: https://the-dataset-is-not-publicly-available.com
auto_download: False
img_size: 32
gezs: [11,12,13,14,15,16]
n_timepoints: 2
seed: 42
test_size: 0.2
val_size: 0.2
shuffle: true

multi_temporal: 2
multi_modal: False

# classes
ignore_index: -1
num_classes: 4
classes:
  - ForestGain
  - ForestLoss
  - StableForest
  - StableNonForest
distribution:
  - 0.12978723
  - 0.2143617
  - 0.31143617
  - 0.34441489
bands:
  optical:
    - B2
    - B3
    - B4
    - B8A
    - B11
    - B12
data_mean:
  optical:
    - 0.05278337 
    - 0.08498019 
    - 0.10346901
    - 0.2802707
    - 0.25964622 
    - 0.16640756
data_std:
  optical:
    - 0.03278688 
    - 0.05424733 
    - 0.08996119 
    - 0.07969411 
    - 0.12222017 
    - 0.12167657
data_min:
  optical: [-0.0889,-0.00132625,-0.0003775,0.,0.,0.]
data_max:
  optical: [0.82843125,0.49058,0.8308925,0.6598975,1.6022125,0.7576325 ]