encoder_weights: ./model/Prithvi_EO_V1_100M.pt
download_url: https://huggingface.co/ibm-nasa-geospatial/Prithvi-EO-1.0-100M/resolve/main/Prithvi_EO_V1_100M.pt?download=true

embed_dim: 768
input_size: 32
in_chans: 6
patch_size: 16
num_heads: 12
depth: 12
mlp_ratio: 4
tubelet_size: 1

resize_pos_embed: 32

num_frames: 2

input_bands:
  optical:
    - B2
    - B3
    - B4
    - B8A
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 768