experiment_name: resnet-epochs20-batch64-lr001-seed5-lrdecay5-tfrecords-all
model_name: resnet
data_dir: tfrecords/all
checkpoint: saved_models/resnet-epochs20-batch64-lr001-seed5-lrdecay5-tfrecords-all/best_model.h5
total_examples: 135232 # number of geotiffs not tfrecords
test_split: 0.2 # float or null
val_split: 0.1
seed: 5
decay_rate: 5

optimizer: adam
optimizer_use_lr_schedular: true
loss_function: binary_crossentropy

epochs: 20
learning_rate: 0.001
batch_size: 64
buffer_size: 135232

early_stopping_patience: null # null or int
