experiment_name: resnet-epochs10-batch32-lr001
model_name: resnet
data_dir: tfrecords/train_test
val_data_dir: tfrecords/val
checkpoint: saved_models/resnet-epochs10-batch32-lr001/best_model.h5
total_examples: 70000 # number of geotiffs not tfrecords
test_split: 0.2 # float or null

optimizer: adam
optimizer_use_lr_schedular: true
loss_function: binary_crossentropy

epochs: 10
learning_rate: 0.001
batch_size: 32
buffer_size: 70000

early_stopping_patience: 5 # null or int
