on:
    push:
        branches:
            - api

name: Tests
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.12" }
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.config.py }}
            
            - name: Install dependencies
              run: |
                  pip install --user -r requirements.txt
                  pip install .
            
            - name: gcloud auth
              uses: 'google-github-actions/auth@v2'
              with:
                project_id: 'pc530-fao-fra-rss'
                credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} 

            - name: Download weights
              run: |
                  mkdir -p -v fao_models/fao_models/saved_models/resnet-epochs20-batch64-lr001-seed5-lrdecay5-tfrecords-all
                  gcloud storage cp gs://forest-nonforest/models/resnet-epochs20-batch64-lr001-seed5-lrdecay5-tfrecords-all/best_model.h5 fao_models/fao_models/saved_models/resnet-epochs20-batch64-lr001-seed5-lrdecay5-tfrecords-all/best_model.h5
                  gcloud storage cp gs://forest-nonforest/models/change_detection_model/checkpoint__best.pth fao_models/fao_models/model/checkpoint__best.pth

            - name: Run Tests
              run: |
                  pytest

